"""add places events tickets tables

Revision ID: 31cc6f6b93be
Revises:
Create Date: 2026-03-29 19:34:26.513714

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31cc6f6b93be"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=50), nullable=False),
        sa.Column("seats_pattern", sa.String(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_places_id"), "places", ["id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column("event_time", sa.DateTime(), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("number_of_visitors", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=30), nullable=False),
        sa.Column("last_name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("seat", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(op.f("ix_tickets_email"), "tickets", ["email"], unique=False)
    op.create_index(
        op.f("ix_tickets_first_name"), "tickets", ["first_name"], unique=False
    )
    op.create_index(
        op.f("ix_tickets_last_name"), "tickets", ["last_name"], unique=False
    )
    op.create_index(op.f("ix_tickets_seat"), "tickets", ["seat"], unique=False)
    op.create_index(
        op.f("ix_tickets_ticket_id"), "tickets", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_ticket_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_seat"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_last_name"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_first_name"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_email"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_places_id"), table_name="places")
    op.drop_table("places")
    # ### end Alembic commands ###
